# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/gui/design/window/StimuliResultsDesign.ui'
#
# Created: Fri Mar 13 21:42:38 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ResultWidget(object):
    def setupUi(self, ResultWidget):
        ResultWidget.setObjectName("ResultWidget")
        ResultWidget.resize(900, 600)
        self.correct_responses_percentage_text = QtWidgets.QLabel(ResultWidget)
        self.correct_responses_percentage_text.setGeometry(QtCore.QRect(50, 20, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_responses_percentage_text.setFont(font)
        self.correct_responses_percentage_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.correct_responses_percentage_text.setObjectName("correct_responses_percentage_text")
        self.correct_response_percentage = QtWidgets.QLabel(ResultWidget)
        self.correct_response_percentage.setGeometry(QtCore.QRect(50, 70, 521, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_response_percentage.setFont(font)
        self.correct_response_percentage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.correct_response_percentage.setObjectName("correct_response_percentage")
        self.correct_authorized_response_percentage = QtWidgets.QLabel(ResultWidget)
        self.correct_authorized_response_percentage.setGeometry(QtCore.QRect(670, 50, 161, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_authorized_response_percentage.setFont(font)
        self.correct_authorized_response_percentage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_authorized_response_percentage.setObjectName("correct_authorized_response_percentage")
        self.correct_authorized_responses_percentage_text = QtWidgets.QLabel(ResultWidget)
        self.correct_authorized_responses_percentage_text.setGeometry(QtCore.QRect(570, 20, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.correct_authorized_responses_percentage_text.setFont(font)
        self.correct_authorized_responses_percentage_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_authorized_responses_percentage_text.setObjectName("correct_authorized_responses_percentage_text")
        self.correct_forbidden_response_percentage = QtWidgets.QLabel(ResultWidget)
        self.correct_forbidden_response_percentage.setGeometry(QtCore.QRect(670, 170, 161, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_forbidden_response_percentage.setFont(font)
        self.correct_forbidden_response_percentage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_forbidden_response_percentage.setObjectName("correct_forbidden_response_percentage")
        self.correct_forbidden_responses_percentage_text = QtWidgets.QLabel(ResultWidget)
        self.correct_forbidden_responses_percentage_text.setGeometry(QtCore.QRect(580, 140, 251, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.correct_forbidden_responses_percentage_text.setFont(font)
        self.correct_forbidden_responses_percentage_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_forbidden_responses_percentage_text.setObjectName("correct_forbidden_responses_percentage_text")
        self.response_time_text = QtWidgets.QLabel(ResultWidget)
        self.response_time_text.setGeometry(QtCore.QRect(50, 270, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.response_time_text.setFont(font)
        self.response_time_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.response_time_text.setObjectName("response_time_text")
        self.response_time = QtWidgets.QLabel(ResultWidget)
        self.response_time.setGeometry(QtCore.QRect(50, 320, 431, 201))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.response_time.setFont(font)
        self.response_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.response_time.setObjectName("response_time")
        self.max_response_time_text = QtWidgets.QLabel(ResultWidget)
        self.max_response_time_text.setGeometry(QtCore.QRect(580, 390, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.max_response_time_text.setFont(font)
        self.max_response_time_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.max_response_time_text.setObjectName("max_response_time_text")
        self.max_response_time = QtWidgets.QLabel(ResultWidget)
        self.max_response_time.setGeometry(QtCore.QRect(550, 420, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.max_response_time.setFont(font)
        self.max_response_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.max_response_time.setObjectName("max_response_time")
        self.min_response_time = QtWidgets.QLabel(ResultWidget)
        self.min_response_time.setGeometry(QtCore.QRect(550, 300, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.min_response_time.setFont(font)
        self.min_response_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.min_response_time.setObjectName("min_response_time")
        self.min_response_time_text = QtWidgets.QLabel(ResultWidget)
        self.min_response_time_text.setGeometry(QtCore.QRect(570, 270, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.min_response_time_text.setFont(font)
        self.min_response_time_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.min_response_time_text.setObjectName("min_response_time_text")
        self.back_button = QtWidgets.QPushButton(ResultWidget)
        self.back_button.setGeometry(QtCore.QRect(10, 560, 160, 32))
        self.back_button.setObjectName("back_button")
        self.correct_authorized_response_number = QtWidgets.QLabel(ResultWidget)
        self.correct_authorized_response_number.setGeometry(QtCore.QRect(525, 70, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_authorized_response_number.setFont(font)
        self.correct_authorized_response_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_authorized_response_number.setObjectName("correct_authorized_response_number")
        self.correct_forbidden_response_number = QtWidgets.QLabel(ResultWidget)
        self.correct_forbidden_response_number.setGeometry(QtCore.QRect(525, 190, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_forbidden_response_number.setFont(font)
        self.correct_forbidden_response_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_forbidden_response_number.setObjectName("correct_forbidden_response_number")

        self.retranslateUi(ResultWidget)
        QtCore.QMetaObject.connectSlotsByName(ResultWidget)

    def retranslateUi(self, ResultWidget):
        _translate = QtCore.QCoreApplication.translate
        ResultWidget.setWindowTitle(_translate("ResultWidget", "Form"))
        self.correct_responses_percentage_text.setText(_translate("ResultWidget", "Résultat"))
        self.correct_response_percentage.setText(_translate("ResultWidget", "TextLabel"))
        self.correct_authorized_response_percentage.setText(_translate("ResultWidget", "TextLabel"))
        self.correct_authorized_responses_percentage_text.setText(_translate("ResultWidget", "Valeurs autorisées"))
        self.correct_forbidden_response_percentage.setText(_translate("ResultWidget", "TextLabel"))
        self.correct_forbidden_responses_percentage_text.setText(_translate("ResultWidget", "Valeurs interdites"))
        self.response_time_text.setText(_translate("ResultWidget", "Temps de réponse moyen"))
        self.response_time.setText(_translate("ResultWidget", "Temps de réponse maximum"))
        self.max_response_time_text.setText(_translate("ResultWidget", "maximum"))
        self.max_response_time.setText(_translate("ResultWidget", "Temps de réponse maximum"))
        self.min_response_time.setText(_translate("ResultWidget", "Temps de réponse maximum"))
        self.min_response_time_text.setText(_translate("ResultWidget", "minimum"))
        self.back_button.setText(_translate("ResultWidget", "Retour à l\'accueil"))
        self.correct_authorized_response_number.setText(_translate("ResultWidget", "TextLabel"))
        self.correct_forbidden_response_number.setText(_translate("ResultWidget", "TextLabel"))

