# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DisplayStimuliSessionResultsDesignWidget.ui'
#
# Created: Wed Mar 11 23:01:19 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        self.correct_responses_percentage_text = QtWidgets.QLabel(Form)
        self.correct_responses_percentage_text.setGeometry(QtCore.QRect(50, 40, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_responses_percentage_text.setFont(font)
        self.correct_responses_percentage_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.correct_responses_percentage_text.setObjectName("correct_responses_percentage_text")
        self.correct_response_percentage = QtWidgets.QLabel(Form)
        self.correct_response_percentage.setGeometry(QtCore.QRect(50, 90, 251, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_response_percentage.setFont(font)
        self.correct_response_percentage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.correct_response_percentage.setObjectName("correct_response_percentage")
        self.correct_valid_response_percentage = QtWidgets.QLabel(Form)
        self.correct_valid_response_percentage.setGeometry(QtCore.QRect(670, 70, 161, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_valid_response_percentage.setFont(font)
        self.correct_valid_response_percentage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_valid_response_percentage.setObjectName("correct_valid_response_percentage")
        self.correct_valid_responses_percentage_text = QtWidgets.QLabel(Form)
        self.correct_valid_responses_percentage_text.setGeometry(QtCore.QRect(570, 40, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.correct_valid_responses_percentage_text.setFont(font)
        self.correct_valid_responses_percentage_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_valid_responses_percentage_text.setObjectName("correct_valid_responses_percentage_text")
        self.correct_invalid_response_percentage = QtWidgets.QLabel(Form)
        self.correct_invalid_response_percentage.setGeometry(QtCore.QRect(670, 190, 161, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.correct_invalid_response_percentage.setFont(font)
        self.correct_invalid_response_percentage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_invalid_response_percentage.setObjectName("correct_invalid_response_percentage")
        self.correct_invalid_responses_percentage_text = QtWidgets.QLabel(Form)
        self.correct_invalid_responses_percentage_text.setGeometry(QtCore.QRect(580, 160, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.correct_invalid_responses_percentage_text.setFont(font)
        self.correct_invalid_responses_percentage_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.correct_invalid_responses_percentage_text.setObjectName("correct_invalid_responses_percentage_text")
        self.response_time_text = QtWidgets.QLabel(Form)
        self.response_time_text.setGeometry(QtCore.QRect(50, 340, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.response_time_text.setFont(font)
        self.response_time_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.response_time_text.setObjectName("response_time_text")
        self.response_time = QtWidgets.QLabel(Form)
        self.response_time.setGeometry(QtCore.QRect(50, 390, 431, 201))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.response_time.setFont(font)
        self.response_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.response_time.setObjectName("response_time")
        self.max_response_time_text = QtWidgets.QLabel(Form)
        self.max_response_time_text.setGeometry(QtCore.QRect(580, 460, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.max_response_time_text.setFont(font)
        self.max_response_time_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.max_response_time_text.setObjectName("max_response_time_text")
        self.max_response_time = QtWidgets.QLabel(Form)
        self.max_response_time.setGeometry(QtCore.QRect(550, 490, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.max_response_time.setFont(font)
        self.max_response_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.max_response_time.setObjectName("max_response_time")
        self.min_response_time = QtWidgets.QLabel(Form)
        self.min_response_time.setGeometry(QtCore.QRect(550, 370, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.min_response_time.setFont(font)
        self.min_response_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.min_response_time.setObjectName("min_response_time")
        self.min_response_time_text = QtWidgets.QLabel(Form)
        self.min_response_time_text.setGeometry(QtCore.QRect(570, 340, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.min_response_time_text.setFont(font)
        self.min_response_time_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.min_response_time_text.setObjectName("min_response_time_text")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.correct_responses_percentage_text.setText(_translate("Form", "Résultat"))
        self.correct_response_percentage.setText(_translate("Form", "TextLabel"))
        self.correct_valid_response_percentage.setText(_translate("Form", "TextLabel"))
        self.correct_valid_responses_percentage_text.setText(_translate("Form", "Valeurs autorisées"))
        self.correct_invalid_response_percentage.setText(_translate("Form", "TextLabel"))
        self.correct_invalid_responses_percentage_text.setText(_translate("Form", "Valeurs interdites"))
        self.response_time_text.setText(_translate("Form", "Temps de réponse moyen"))
        self.response_time.setText(_translate("Form", "Temps de réponse maximum"))
        self.max_response_time_text.setText(_translate("Form", "maximum"))
        self.max_response_time.setText(_translate("Form", "Temps de réponse maximum"))
        self.min_response_time.setText(_translate("Form", "Temps de réponse maximum"))
        self.min_response_time_text.setText(_translate("Form", "minimum"))

